DROP DATABASE IF EXISTS employees_db
CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE deparment (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    departmentName VARCHAR(30) NOT NULL
);

CREATE TABLE roleName (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL(10,2) NOT NULL,
    deparment_id INT NOT NULL FOREIGN KEY REFERENCES deparment(id), 
    ON DELETE SET NULL
);

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NOT NULL FOREIGN KEY REFERENCES roleName(id),
    manager_id INT NOT NULL FOREIGN KEY REFERENCES employee(id),
    ON DELETE SET NULL    
);